
steps:

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--network=cloudbuild'
  - '--cache-from'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_FOLDER}/${_REPO}:$BRANCH_NAME'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_FOLDER}/${_REPO}:$BRANCH_NAME'
  - '-f'
  - 'docker/Dockerfile'
  - '--build-arg'
  - 'ENVIRONMENT=${_RUNTIME_ENVIRONMENT}'
  - '.'
  id: 'build'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_FOLDER}/${_REPO}:$BRANCH_NAME']
  id: 'deploy'
  waitFor: ['build']

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_FOLDER}/${_REPO}:$BRANCH_NAME'
options:
 machineType: 'E2_HIGHCPU_8'
timeout: 1800s

substitutions:
  _REPO: bytecodeio-p-tera-api-dev-repo